#!/usr/bin/env python3
"""check_editorial_diff.py — invariant guard for the Stage-4 editorial pass.

The editorial pass rewrites prose and nothing else. This module pins what
"nothing else" means, so a rewrite that moves meaning is reverted instead of
shipped:

  * outside the editable allow-list, ``threat-model.yaml`` and the JSON
    fragments must stay deep-equal;
  * inside an editable field, every identifier, link target, code span, path
    or ``file:line`` locator and number survives as an unchanged multiset;
  * a field that carried text keeps carrying text — blanking is not a rewrite;
  * headings in Markdown fragments stay byte-identical, because anchors, the
    TOC and the ``**Controls covered:**`` links are built from them;
  * mitigation step counts follow from list-length equality, which keeps the
    P1/P2 floor that ``validate_mitigation_quality.py`` enforces as a blocking
    gate intact. Catching it here reverts one edit; leaving it to that gate
    would abort the run.

Usage::

    check_editorial_diff.py snapshot --output-dir DIR
    check_editorial_diff.py verify   --output-dir DIR [--restore]
    check_editorial_diff.py restore  --output-dir DIR

``snapshot`` stores the guarded files verbatim in ``.editorial-snapshot.json``.
``verify`` recomputes both sides from those bytes, so the report can name the
exact field and token that changed. Exit 0 when clean, 2 on any violation, 1 on
a usage or I/O error. With ``--restore`` a violating run is rolled back to the
snapshot and still exits 2 — the caller continues with the unedited text.
"""

from __future__ import annotations

import argparse
import copy
import datetime as _dt
import json
import re
import sys
from pathlib import Path
from typing import Any, Iterator

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _atomic_io import atomic_write_json, atomic_write_text  # noqa: E402

# Runtime state lives under `.dispatch-context/`, which `runtime_cleanup.py`
# already reaps — a snapshot at the output-dir root would need its own
# cleanup-whitelist entry to avoid outliving the run.
SNAPSHOT_NAME = ".dispatch-context/editorial/snapshot.json"
YAML_NAME = "threat-model.yaml"

# Fragments the editorial pass may rewrite. Every other fragment is either
# regenerated by `pregenerate_fragments.py --force` before each compose or
# owned by a deterministic emitter, so an edit there would not survive.
EDITABLE_FRAGMENTS = (
    ".fragments/security-architecture.md",
    ".fragments/ms-verdict.json",
    ".fragments/ms-anti-patterns.json",
)

# Prose keys of the verdict block. Shared by `threat-model.yaml::verdict` and
# `.fragments/ms-verdict.json`, which carry the same shape.
_VERDICT_PROSE = ("opening", "bullets_intro", "closing")

_ID_RE = re.compile(r"\b(?:AC-T|CWE|CVE|F|T|M|C|TB|AC)-\d+(?:-\d+)?\b")
_CODE_SPAN_RE = re.compile(r"`([^`\n]+)`")
_LINK_TARGET_RE = re.compile(r"\]\(([^)\s]+)")
_URL_RE = re.compile(r"https?://[^\s)\]>]+")
_PATH_RE = re.compile(r"\b[\w./-]+\.[A-Za-z0-9]{1,6}(?::\d+(?:-\d+)?)?\b")
_NUMBER_RE = re.compile(r"\d+(?:\.\d+)*")


class GuardError(RuntimeError):
    """Unusable input — a missing file, unparseable JSON, absent snapshot."""


# ---------------------------------------------------------------------------
# Editable-field addressing
# ---------------------------------------------------------------------------


def _verdict_paths(block: Any, prefix: tuple) -> Iterator[tuple]:
    if not isinstance(block, dict):
        return
    for key in _VERDICT_PROSE:
        if isinstance(block.get(key), str):
            yield (*prefix, key)
    for i, bullet in enumerate(block.get("bullets") or []):
        if isinstance(bullet, dict) and isinstance(bullet.get("body"), str):
            yield (*prefix, "bullets", i, "body")


def yaml_editable_paths(data: Any) -> Iterator[tuple]:
    """Yield the address of every field the editorial pass may rewrite.

    Titles stay out: `_canonical_finding_title` derives the §8 heading from CWE
    and evidence, `recommend_fixes.py` and the §3 "Primary mitigation" line
    match on the mitigation title, and §6 anchors follow heading text.
    """
    if not isinstance(data, dict):
        return
    for i, threat in enumerate(data.get("threats") or []):
        if not isinstance(threat, dict):
            continue
        for key in ("scenario", "evidence_summary", "impact_description", "breach_distance_reason"):
            if isinstance(threat.get(key), str):
                yield ("threats", i, key)
    for i, mitigation in enumerate(data.get("mitigations") or []):
        if not isinstance(mitigation, dict):
            continue
        if isinstance(mitigation.get("verification"), str):
            yield ("mitigations", i, "verification")
        for j, step in enumerate(mitigation.get("steps") or []):
            if isinstance(step, str):
                yield ("mitigations", i, "steps", j)
    yield from _verdict_paths(data.get("verdict"), ("verdict",))


def fragment_editable_paths(name: str, data: Any) -> Iterator[tuple]:
    """Editable addresses inside a JSON fragment."""
    if name.endswith("ms-verdict.json"):
        yield from _verdict_paths(data, ())
    elif name.endswith("ms-anti-patterns.json") and isinstance(data, dict):
        for i, entry in enumerate(data.get("anti_patterns") or []):
            if isinstance(entry, dict) and isinstance(entry.get("description"), str):
                yield ("anti_patterns", i, "description")


def _read_path(data: Any, path: tuple) -> Any:
    node = data
    for key in path:
        try:
            node = node[key]
        except (KeyError, IndexError, TypeError):
            return None
    return node


def _blank_path(data: Any, path: tuple) -> None:
    node = data
    for key in path[:-1]:
        try:
            node = node[key]
        except (KeyError, IndexError, TypeError):
            return
    try:
        node[path[-1]] = ""
    except (KeyError, IndexError, TypeError):
        return


def _skeleton(data: Any, paths: list[tuple]) -> Any:
    """The document with every editable field blanked."""
    out = copy.deepcopy(data)
    for path in paths:
        _blank_path(out, path)
    return out


# ---------------------------------------------------------------------------
# Invariants
# ---------------------------------------------------------------------------


def text_invariants(text: str) -> dict[str, list[str]]:
    """Tokens a rewrite must carry over unchanged, as sorted multisets.

    Extracted from the text with its backticks stripped. `prose-style.md` Rule 6
    requires a code token to be fenced, so a rewrite that obeys the style adds
    backticks the original lacked; pinning the fenced form would revert exactly
    the improvements this pass exists to make. What is pinned is the token.
    """
    plain = text.replace("`", "")
    return {
        "identifiers": sorted(_ID_RE.findall(plain)),
        "link_targets": sorted(_LINK_TARGET_RE.findall(plain)),
        "urls": sorted(_URL_RE.findall(plain)),
        "paths": sorted(_PATH_RE.findall(plain)),
        "numbers": sorted(_NUMBER_RE.findall(plain)),
    }


def dropped_code_spans(old: str, new: str) -> list[str]:
    """Fenced spans of ``old`` that no longer appear in ``new`` in any form.

    Presence, not count: a span repeated twice and kept once passes. The token
    classes above carry the exact accounting; this catches a span the other
    patterns do not describe, such as a bare symbol name.
    """
    plain_new = new.replace("`", "")
    return sorted({span for span in _CODE_SPAN_RE.findall(old) if span not in plain_new})


def _first_structural_difference(before: Any, after: Any, path: tuple = ()) -> tuple | None:
    """Address of the first blanked-document difference, or None."""
    if type(before) is not type(after):
        return path
    if isinstance(before, dict):
        if set(before) != set(after):
            return path
        for key in before:
            found = _first_structural_difference(before[key], after[key], (*path, key))
            if found is not None:
                return found
        return None
    if isinstance(before, list):
        if len(before) != len(after):
            return path
        for i, item in enumerate(before):
            found = _first_structural_difference(item, after[i], (*path, i))
            if found is not None:
                return found
        return None
    return None if before == after else path


def _fmt(path: tuple) -> str:
    out = ""
    for key in path:
        out += f"[{key}]" if isinstance(key, int) else (f".{key}" if out else str(key))
    return out or "<root>"


def _compare_structured(
    file_name: str,
    before: Any,
    after: Any,
    paths_of: Any,
) -> list[dict]:
    violations: list[dict] = []
    before_paths = list(paths_of(before))
    after_paths = list(paths_of(after))

    drift = _first_structural_difference(_skeleton(before, before_paths), _skeleton(after, after_paths))
    if drift is not None:
        violations.append(
            {
                "file": file_name,
                "kind": "structure_changed",
                "detail": f"{_fmt(drift)} differs outside the editable allow-list",
            }
        )
        return violations

    for path in before_paths:
        old = _read_path(before, path)
        new = _read_path(after, path)
        if not isinstance(new, str):
            violations.append({"file": file_name, "kind": "field_removed", "detail": _fmt(path)})
            continue
        if old.strip() and not new.strip():
            violations.append({"file": file_name, "kind": "field_blanked", "detail": _fmt(path)})
            continue
        violations.extend(_token_violations(file_name, _fmt(path), old, new))
    return violations


def _token_violations(file_name: str, where: str, old: str, new: str) -> list[dict]:
    out: list[dict] = []
    before = text_invariants(old)
    after = text_invariants(new)
    for kind, expected in before.items():
        actual = after[kind]
        if expected == actual:
            continue
        lost = sorted(_multiset_difference(expected, actual))
        added = sorted(_multiset_difference(actual, expected))
        out.append(
            {
                "file": file_name,
                "kind": f"{kind}_changed",
                "detail": f"{where}: lost {lost or '[]'}, added {added or '[]'}",
            }
        )
    dropped = dropped_code_spans(old, new)
    if dropped:
        out.append({"file": file_name, "kind": "code_spans_dropped", "detail": f"{where}: lost {dropped}"})
    return out


def _multiset_difference(left: list[str], right: list[str]) -> list[str]:
    remaining = list(right)
    missing = []
    for item in left:
        if item in remaining:
            remaining.remove(item)
        else:
            missing.append(item)
    return missing


def _compare_markdown(file_name: str, before: str, after: str) -> list[dict]:
    violations: list[dict] = []
    before_headings = [line for line in before.splitlines() if line.lstrip().startswith("#")]
    after_headings = [line for line in after.splitlines() if line.lstrip().startswith("#")]
    if before_headings != after_headings:
        violations.append(
            {
                "file": file_name,
                "kind": "headings_changed",
                "detail": "heading lines drive anchors, the TOC and controls-covered links",
            }
        )
    if before.strip() and not after.strip():
        violations.append({"file": file_name, "kind": "field_blanked", "detail": "<file>"})
        return violations
    violations.extend(_token_violations(file_name, "<file>", before, after))
    return violations


# ---------------------------------------------------------------------------
# Snapshot / verify
# ---------------------------------------------------------------------------


def guarded_files(output_dir: Path) -> list[str]:
    """Relative names of the files the pass may touch, in a stable order."""
    names = [YAML_NAME, *EDITABLE_FRAGMENTS]
    return [name for name in names if (output_dir / name).is_file()]


def build_snapshot(output_dir: Path) -> dict:
    files = guarded_files(output_dir)
    if YAML_NAME not in files:
        raise GuardError(f"{YAML_NAME} is missing — nothing to guard")
    return {
        "schema_version": 1,
        "generated": _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "files": {name: (output_dir / name).read_text(encoding="utf-8") for name in files},
    }


def _parse(name: str, text: str) -> Any:
    if name.endswith(".json"):
        return json.loads(text)
    import yaml  # local import: the guard must still load where PyYAML is absent

    return yaml.safe_load(text)


def verify(snapshot: dict, output_dir: Path) -> list[dict]:
    """Compare the current guarded files against the snapshot."""
    stored = snapshot.get("files")
    if not isinstance(stored, dict) or not stored:
        raise GuardError("snapshot carries no files")

    violations: list[dict] = []
    for name, before_text in stored.items():
        path = output_dir / name
        if not path.is_file():
            violations.append({"file": name, "kind": "file_removed", "detail": str(path)})
            continue
        after_text = path.read_text(encoding="utf-8")
        if after_text == before_text:
            continue
        if name.endswith(".md"):
            violations.extend(_compare_markdown(name, before_text, after_text))
            continue
        try:
            before = _parse(name, before_text)
            after = _parse(name, after_text)
        except Exception as exc:  # noqa: BLE001 — any parse failure is a violation
            violations.append({"file": name, "kind": "unparseable", "detail": f"{type(exc).__name__}: {exc}"})
            continue
        paths_of = yaml_editable_paths if name == YAML_NAME else (lambda d, _n=name: fragment_editable_paths(_n, d))
        violations.extend(_compare_structured(name, before, after, paths_of))
    return violations


def restore(snapshot: dict, output_dir: Path) -> list[str]:
    """Write the snapshot bytes back. Returns the files actually rewritten."""
    restored = []
    for name, text in (snapshot.get("files") or {}).items():
        path = output_dir / name
        if path.is_file() and path.read_text(encoding="utf-8") == text:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        atomic_write_text(path, text)
        restored.append(name)
    return restored


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(prog="check_editorial_diff.py", description=__doc__)
    parser.add_argument("command", choices=["snapshot", "verify", "restore"])
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--snapshot", help=f"snapshot path (default: <output-dir>/{SNAPSHOT_NAME})")
    parser.add_argument(
        "--restore",
        action="store_true",
        help="verify only: roll the guarded files back to the snapshot when a violation is found",
    )
    args = parser.parse_args(argv)

    output_dir = Path(args.output_dir)
    if not output_dir.is_dir():
        print(f"check_editorial_diff.py: output dir not found: {output_dir}", file=sys.stderr)
        return 1
    snapshot_path = Path(args.snapshot) if args.snapshot else output_dir / SNAPSHOT_NAME

    try:
        if args.command == "snapshot":
            snapshot = build_snapshot(output_dir)
            snapshot_path.parent.mkdir(parents=True, exist_ok=True)
            atomic_write_json(snapshot_path, snapshot)
            json.dump(
                {"status": "recorded", "files": sorted(snapshot["files"]), "snapshot": str(snapshot_path)},
                sys.stdout,
                indent=2,
                sort_keys=True,
            )
            sys.stdout.write("\n")
            return 0

        if not snapshot_path.is_file():
            raise GuardError(f"no snapshot at {snapshot_path} — run `snapshot` before the editorial dispatch")
        snapshot = json.loads(snapshot_path.read_text(encoding="utf-8"))

        if args.command == "restore":
            # Unconditional roll-back. `verify --restore` only fires on an
            # invariant violation; a later gate that rejects the edited bytes
            # needs this, so a failed polish costs the polish and not the run.
            restored = restore(snapshot, output_dir)
            json.dump({"status": "restored", "restored": restored}, sys.stdout, indent=2, sort_keys=True)
            sys.stdout.write("\n")
            return 0
        violations = verify(snapshot, output_dir)
        report = {
            "status": "clean" if not violations else "violations",
            "violation_count": len(violations),
            "violations": violations,
            "restored": [],
        }
        if violations and args.restore:
            report["restored"] = restore(snapshot, output_dir)
        json.dump(report, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
        for violation in violations:
            print(
                f"[editorial-guard] {violation['file']}: {violation['kind']} — {violation['detail']}", file=sys.stderr
            )
        return 2 if violations else 0
    except GuardError as exc:
        print(f"check_editorial_diff.py: {exc}", file=sys.stderr)
        return 1
    except (OSError, ValueError) as exc:
        print(f"check_editorial_diff.py: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
